# COMMIT3
name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    # 249 How to quit test(npm test) watch mode in CI
    env: 
      CI: true
      # 250
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        # 249 Set property
        node-version: [14.x, 16.x]
        # 250 
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # get property
      - name: Use Node.JS version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          # node-version: "16"
          # get property
          node-version: ${{matrix.node-version}}
      # 251 Mocking out DB
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.9.0
        with: 
          ${{matrix.mongodb-version}}
      - run: npm install
      - run: npm run build --prefix client\
      - run: npm test


  # deploy:
  #   needs: build // synchoronous is possible

  
